Improve failure path

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -48,7 +48,8 @@ else
       echo "Rollback succeeded. Retrying deploy"
       deploy_branch
     else
-      echo "Rollback succeeded. Consider manually running 'helm delete $BRANCH_RELEASE_NAME'"
+      echo "Rollback failed. Consider manually running 'helm delete $BRANCH_RELEASE_NAME'"
+      exit 1
     fi
   fi
 fi
