Try new deploy retry

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,17 +1,18 @@
 #!/bin/sh
 
 ENVIRONMENT=$1
+# Convert the branch name into a string that can be turned into a valid URL
+  BRANCH_RELEASE_NAME=$(echo $CIRCLE_BRANCH | tr '[:upper:]' '[:lower:]' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | cut -c1-18 | sed 's/-$//')
+
 
 deploy_branch() {
-# Convert the branch name into a string that can be turned into a valid URL
-  RELEASE_NAME=$(echo $CIRCLE_BRANCH | tr '[:upper:]' '[:lower:]' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | cut -c1-18 | sed 's/-$//')
 # Set the deployment host, this will add the prefix of the branch name e.g el-257-deploy-with-circleci or just main
-  RELEASE_HOST="$RELEASE_NAME-check-client-qualifies-legal-aid-uat.cloud-platform.service.justice.gov.uk"
+  RELEASE_HOST="$BRANCH_RELEASE_NAME-check-client-qualifies-legal-aid-uat.cloud-platform.service.justice.gov.uk"
 # Set the ingress name, needs release name, namespace and -green suffix
-  IDENTIFIER="$RELEASE_NAME-laa-estimate-eligibility-laa-estimate-financial-eligibility-for-legal-aid-uat-green"
-  echo "Deploying CIRCLE_SHA1: $CIRCLE_SHA1 under release name: '$RELEASE_NAME'..."
+  IDENTIFIER="$BRANCH_RELEASE_NAME-laa-estimate-eligibility-laa-estimate-financial-eligibility-for-legal-aid-uat-green"
+  echo "Deploying CIRCLE_SHA1: $CIRCLE_SHA1 under release name: '$BRANCH_RELEASE_NAME'..."
 
-  helm upgrade $RELEASE_NAME ./helm_deploy/laa-estimate-eligibility/. \
+  helm upgrade $BRANCH_RELEASE_NAME ./helm_deploy/laa-estimate-eligibility/. \
                 --install --wait \
                 --namespace=${K8S_NAMESPACE} \
                 --values ./helm_deploy/laa-estimate-eligibility/values/uat.yaml \
@@ -35,4 +36,16 @@ if [[ "$CIRCLE_BRANCH" == "main" ]]; then
   deploy_main
 else
   deploy_branch
+  if [ $? -eq 0 ]; then
+    echo "Deploy succeeded"
+  else
+    echo "Deploy failed. Attempting rollback"
+    helm rollback $BRANCH_RELEASE_NAME
+    if [ $? -eq 0 ]; then
+      echo "Rollback succeeded. Retrying deploy"
+      deploy_branch
+    else
+      echo "Rollback succeeded. Consider manually running 'helm delete $BRANCH_RELEASE_NAME'"
+    fi
+  fi
 fi
